### ISSUE TITLE
Adaptive Thresholding issue

### ISSUE THREAD

**Issue by AkiNikolaidis** [dpisner453/PyNets#18]
Looking at the adaptive_thresholding function- right now it seems the user inputs a threshold, and the adaptive threshold function will adjust this threshold until less than 25% of the edges are missing.

Seems that making the 25% the input value would be useful to users. Instead of the user setting a start point for the adaptive threshold, we could choose a random high threshold,- like 99, and adapt until we meet the criterion that gets passed to the function?

**Comment by dpisner453** [comment]
Exactly. That function is very much incomplete and realistically will need to use additional information (I.e. beyond a certain percentage of retained connections) as a stopping criterion in order to avoid an inflated rate of false positives in situations where the subject's image is noisier than others. I think a better criterion would be network resilience-- http://www.sciencedirect.com/science/article/pii/S1053811916304359
